package com.myspace.monthlyplansproject;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class MonthlyPlan implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Label("id")
	private java.lang.String id;
	@org.kie.api.definition.type.Label("year")
	private int year;
	@org.kie.api.definition.type.Label("month")
	private int month;
	@org.kie.api.definition.type.Label("name")
	private java.lang.String name;
	@org.kie.api.definition.type.Label("status")
	private java.lang.String status;

	@org.kie.api.definition.type.Label("planProcessInstanceId")
	private long planProcessInstanceId;

	@org.kie.api.definition.type.Label("institution")
	private java.lang.String institution;

	@org.kie.api.definition.type.Label("Industries")
	private java.util.List<java.lang.String> industriesId;

	@org.kie.api.definition.type.Label("levelFourIndustries")
	private java.util.List<java.lang.String> levelFourIndustriesId;

	@org.kie.api.definition.type.Label(value = "registryIds")
	private java.util.List<java.lang.String> registryIds;

	public MonthlyPlan() {
	}

	public java.lang.String getId() {
		return this.id;
	}

	public void setId(java.lang.String id) {
		this.id = id;
	}

	public int getYear() {
		return this.year;
	}

	public void setYear(int year) {
		this.year = year;
	}

	public int getMonth() {
		return this.month;
	}

	public void setMonth(int month) {
		this.month = month;
	}

	public java.lang.String getName() {
		return this.name;
	}

	public void setName(java.lang.String name) {
		this.name = name;
	}

	public java.lang.String getStatus() {
		return this.status;
	}

	public void setStatus(java.lang.String status) {
		this.status = status;
	}

	public long getPlanProcessInstanceId() {
		return this.planProcessInstanceId;
	}

	public void setPlanProcessInstanceId(long planProcessInstanceId) {
		this.planProcessInstanceId = planProcessInstanceId;
	}

	public java.lang.String getInstitution() {
		return this.institution;
	}

	public void setInstitution(java.lang.String institution) {
		this.institution = institution;
	}

	public java.util.List<java.lang.String> getIndustriesId() {
		return this.industriesId;
	}

	public void setIndustriesId(java.util.List<java.lang.String> industriesId) {
		this.industriesId = industriesId;
	}

	public java.util.List<java.lang.String> getLevelFourIndustriesId() {
		return this.levelFourIndustriesId;
	}

	public void setLevelFourIndustriesId(
			java.util.List<java.lang.String> levelFourIndustriesId) {
		this.levelFourIndustriesId = levelFourIndustriesId;
	}

	public java.util.List<java.lang.String> getRegistryIds() {
		return this.registryIds;
	}

	public void setRegistryIds(java.util.List<java.lang.String> registryIds) {
		this.registryIds = registryIds;
	}

	public MonthlyPlan(java.lang.String id, int year, int month,
			java.lang.String name, java.lang.String status,
			long planProcessInstanceId, java.lang.String institution,
			java.util.List<java.lang.String> industriesId,
			java.util.List<java.lang.String> levelFourIndustriesId,
			java.util.List<java.lang.String> registryIds) {
		this.id = id;
		this.year = year;
		this.month = month;
		this.name = name;
		this.status = status;
		this.planProcessInstanceId = planProcessInstanceId;
		this.institution = institution;
		this.industriesId = industriesId;
		this.levelFourIndustriesId = levelFourIndustriesId;
		this.registryIds = registryIds;
	}

}